name: Release

on:
  release:
    types:
      - published

jobs:
  build_and_push_docker:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: housemanager/backend:${{ github.event.release.tag_name }}

  release_to_sentry:
    name: Release to Sentry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ github.ref }}

  deployment_update:
    name: Deployment update
    runs-on: ubuntu-latest
    needs:
      - build_and_push_docker
    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DEPLOYMENT_REPO }}
          ssh-key: ${{ secrets.DEPLOYMENT_REPO_SSH }}
          persist-credentials: true
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"
      - name: Update Kubernetes resources
        run: |
          cd backend
          kustomize edit set image backend-image=housemanager/backend:${{ github.event.release.tag_name }}
          cat kustomization.yaml
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Set frontend image to ${{ github.event.release.tag_name }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          ssh: true
          repository: ${{ secrets.DEPLOYMENT_REPO }}
